language: python

services:
  - docker

script:
  - docker run --privileged -v $(pwd):/travis $CONTAINER /travis/mock_build.sh

jobs:
  include:
    - env: CONTAINER=fedora:31
    - env: CONTAINER=fedora:32
